# fly.toml app configuration file generated for wispy-wildflower-4253 on 2023-07-15T01:32:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wispy-wildflower-4253"
primary_region = "ord"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
